# Generated by scripts/render-r-stubs.py from the plskit-bind registry.
# Do not edit by hand: re-run `python3 scripts/render-r-stubs.py`
# after a registry change.

#' Standardize X and Y
#'
#' R binding of `preprocess`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "1. Preprocessing" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,Y,weights See the canonical reference.
#' @return A list of class `c("preprocess_result", "plskit_result")`.
#' @export
preprocess <- function(
  X = NULL,
  Y = NULL,
  weights = NULL
) {
  .plskit_call("preprocess", list(
    X = X,
    Y = Y,
    weights = weights
  ))
}

#' Fit a PLS1 model
#'
#' R binding of `pls1_fit`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2.1 Fit" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k,k_max,find_k_args,pre_standardized,seed,weights See the canonical reference.
#' @return A list of class `c("pls1_result", "plskit_result")`.
#' @export
pls1_fit <- function(
  X,
  y,
  k = 1L,
  k_max = NULL,
  find_k_args = NULL,
  pre_standardized = FALSE,
  seed = NULL,
  weights = NULL
) {
  .plskit_call("pls1_fit", list(
    X = X,
    y = y,
    k = k,
    k_max = k_max,
    find_k_args = find_k_args,
    pre_standardized = pre_standardized,
    seed = seed,
    weights = weights
  ))
}

#' Predict from a fitted PLS1 model
#'
#' R binding of `pls1_predict`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2.2 Predict" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param model,X_new See the canonical reference.
#' @return A numeric vector.
#' @export
pls1_predict <- function(
  model,
  X_new
) {
  .plskit_call("pls1_predict", list(
    model = model,
    X_new = X_new
  ))
}

#' Choose k for PLS1 by cross-validation or BIC
#'
#' R binding of `pls1_find_k_optimal`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2.3 K-selection" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k_max,selector,diagnostic,args,pre_standardized,seed,disable_parallelism,verbose,weights See the canonical reference.
#' @return A list of class `c("find_k_optimal_result", "plskit_result")`.
#' @export
pls1_find_k_optimal <- function(
  X,
  y,
  k_max,
  selector = "r2_se",
  diagnostic = NULL,
  args = NULL,
  pre_standardized = FALSE,
  seed = NULL,
  disable_parallelism = FALSE,
  verbose = FALSE,
  weights = NULL
) {
  .plskit_call("pls1_find_k_optimal", list(
    X = X,
    y = y,
    k_max = k_max,
    selector = selector,
    diagnostic = diagnostic,
    args = args,
    pre_standardized = pre_standardized,
    seed = seed,
    disable_parallelism = disable_parallelism,
    verbose = verbose,
    weights = weights
  ))
}

#' Choose k for PLS1 by sequential testing
#'
#' R binding of `pls1_find_k_sequence`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2.3 K-selection" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k_max,test_method,alpha,args,pre_standardized,seed,disable_parallelism,verbose,weights See the canonical reference.
#' @return A list of class `c("find_k_sequence_result", "plskit_result")`.
#' @export
pls1_find_k_sequence <- function(
  X,
  y,
  k_max,
  test_method = "split_nb",
  alpha = NULL,
  args = NULL,
  pre_standardized = FALSE,
  seed = NULL,
  disable_parallelism = FALSE,
  verbose = FALSE,
  weights = NULL
) {
  .plskit_call("pls1_find_k_sequence", list(
    X = X,
    y = y,
    k_max = k_max,
    test_method = test_method,
    alpha = alpha,
    args = args,
    pre_standardized = pre_standardized,
    seed = seed,
    disable_parallelism = disable_parallelism,
    verbose = verbose,
    weights = weights
  ))
}

#' Fit a sparse PLS1 model
#'
#' R binding of `spls1_fit`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2b.1 Sparse fit" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k,keep,pre_standardized,weights See the canonical reference.
#' @return A list of class `c("pls1_result", "plskit_result")`.
#' @export
spls1_fit <- function(
  X,
  y,
  k,
  keep,
  pre_standardized = FALSE,
  weights = NULL
) {
  .plskit_call("spls1_fit", list(
    X = X,
    y = y,
    k = k,
    keep = keep,
    pre_standardized = pre_standardized,
    weights = weights
  ))
}

#' Choose the sPLS1 keep-count by cross-validation
#'
#' R binding of `spls1_find_keep_optimal`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2b.2 Keep-count tuning" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k,args,seed,disable_parallelism,verbose,weights See the canonical reference.
#' @return A list of class `c("find_keep_optimal_result", "plskit_result")`.
#' @export
spls1_find_keep_optimal <- function(
  X,
  y,
  k,
  args = NULL,
  seed = NULL,
  disable_parallelism = FALSE,
  verbose = FALSE,
  weights = NULL
) {
  .plskit_call("spls1_find_keep_optimal", list(
    X = X,
    y = y,
    k = k,
    args = args,
    seed = seed,
    disable_parallelism = disable_parallelism,
    verbose = verbose,
    weights = weights
  ))
}

#' Choose k for sPLS1 by cross-validation or BIC
#'
#' R binding of `spls1_find_k_optimal`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2b.3 K-selection at fixed keep" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k_max,keep,selector,diagnostic,args,pre_standardized,seed,disable_parallelism,verbose,weights See the canonical reference.
#' @return A list of class `c("find_k_optimal_result", "plskit_result")`.
#' @export
spls1_find_k_optimal <- function(
  X,
  y,
  k_max,
  keep,
  selector = "r2_se",
  diagnostic = NULL,
  args = NULL,
  pre_standardized = FALSE,
  seed = NULL,
  disable_parallelism = FALSE,
  verbose = FALSE,
  weights = NULL
) {
  .plskit_call("spls1_find_k_optimal", list(
    X = X,
    y = y,
    k_max = k_max,
    keep = keep,
    selector = selector,
    diagnostic = diagnostic,
    args = args,
    pre_standardized = pre_standardized,
    seed = seed,
    disable_parallelism = disable_parallelism,
    verbose = verbose,
    weights = weights
  ))
}

#' Choose k for sPLS1 by sequential testing
#'
#' R binding of `spls1_find_k_sequence`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2b.3 K-selection at fixed keep" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k_max,keep,test_method,alpha,args,pre_standardized,seed,disable_parallelism,verbose,weights See the canonical reference.
#' @return A list of class `c("find_k_sequence_result", "plskit_result")`.
#' @export
spls1_find_k_sequence <- function(
  X,
  y,
  k_max,
  keep,
  test_method = "split_nb",
  alpha = NULL,
  args = NULL,
  pre_standardized = FALSE,
  seed = NULL,
  disable_parallelism = FALSE,
  verbose = FALSE,
  weights = NULL
) {
  .plskit_call("spls1_find_k_sequence", list(
    X = X,
    y = y,
    k_max = k_max,
    keep = keep,
    test_method = test_method,
    alpha = alpha,
    args = args,
    pre_standardized = pre_standardized,
    seed = seed,
    disable_parallelism = disable_parallelism,
    verbose = verbose,
    weights = weights
  ))
}

#' Fit a PLS3 (PLS-SVD) model
#'
#' R binding of `pls3_fit`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2c.1 Fit" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,Y,k,pre_standardized_X,pre_standardized_Y,weights See the canonical reference.
#' @return A list of class `c("pls3_result", "plskit_result")`.
#' @export
pls3_fit <- function(
  X,
  Y,
  k = 1L,
  pre_standardized_X = FALSE,
  pre_standardized_Y = FALSE,
  weights = NULL
) {
  .plskit_call("pls3_fit", list(
    X = X,
    Y = Y,
    k = k,
    pre_standardized_X = pre_standardized_X,
    pre_standardized_Y = pre_standardized_Y,
    weights = weights
  ))
}

#' Fit a PLS-SVD model (alias of pls3_fit)
#'
#' R binding of `plssvd_fit`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2c.1 Fit" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,Y,k,pre_standardized_X,pre_standardized_Y,weights See the canonical reference.
#' @return A list of class `c("pls3_result", "plskit_result")`.
#' @export
plssvd_fit <- function(
  X,
  Y,
  k = 1L,
  pre_standardized_X = FALSE,
  pre_standardized_Y = FALSE,
  weights = NULL
) {
  .plskit_call("plssvd_fit", list(
    X = X,
    Y = Y,
    k = k,
    pre_standardized_X = pre_standardized_X,
    pre_standardized_Y = pre_standardized_Y,
    weights = weights
  ))
}

#' Project new data onto a fitted PLS3 model
#'
#' R binding of `pls3_transform`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2c.2 Transform" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param model,X_new,Y_new,which See the canonical reference.
#' @return A list of class `c("pls3_scores", "plskit_result")`.
#' @export
pls3_transform <- function(
  model,
  X_new = NULL,
  Y_new = NULL,
  which = "both"
) {
  .plskit_call("pls3_transform", list(
    model = model,
    X_new = X_new,
    Y_new = Y_new,
    which = which
  ))
}

#' Project new data onto a fitted PLS-SVD model
#'
#' R binding of `plssvd_transform`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2c.2 Transform" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param model,X_new,Y_new,which See the canonical reference.
#' @return A list of class `c("pls3_scores", "plskit_result")`.
#' @export
plssvd_transform <- function(
  model,
  X_new = NULL,
  Y_new = NULL,
  which = "both"
) {
  .plskit_call("plssvd_transform", list(
    model = model,
    X_new = X_new,
    Y_new = Y_new,
    which = which
  ))
}

#' Fit a sparse PLS3 model
#'
#' R binding of `spls3_fit`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "2c.3 Sparse fit" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,Y,k,keep_X,keep_Y,pre_standardized_X,pre_standardized_Y,max_iter,tol,weights See the canonical reference.
#' @return A list of class `c("pls3_result", "plskit_result")`.
#' @export
spls3_fit <- function(
  X,
  Y,
  k,
  keep_X,
  keep_Y,
  pre_standardized_X = FALSE,
  pre_standardized_Y = FALSE,
  max_iter = NULL,
  tol = NULL,
  weights = NULL
) {
  .plskit_call("spls3_fit", list(
    X = X,
    Y = Y,
    k = k,
    keep_X = keep_X,
    keep_Y = keep_Y,
    pre_standardized_X = pre_standardized_X,
    pre_standardized_Y = pre_standardized_Y,
    max_iter = max_iter,
    tol = tol,
    weights = weights
  ))
}

#' Confirmatory test of a PLS1 signal
#'
#' R binding of `pls1_confirmatory_test`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "3.1 Confirmatory omnibus test" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k,method,args,ci,n_boot,m_rate,level,max_failure_rate,pre_standardized,seed,disable_parallelism,verbose,weights,max_skip_rate See the canonical reference.
#' @return A list of class `c("confirmatory_test_result", "plskit_result")`.
#' @export
pls1_confirmatory_test <- function(
  X,
  y,
  k = 1L,
  method,
  args = NULL,
  ci = FALSE,
  n_boot = NULL,
  m_rate = NULL,
  level = NULL,
  max_failure_rate = NULL,
  pre_standardized = FALSE,
  seed = NULL,
  disable_parallelism = FALSE,
  verbose = FALSE,
  weights = NULL,
  max_skip_rate = NULL
) {
  .plskit_call("pls1_confirmatory_test", list(
    X = X,
    y = y,
    k = k,
    method = method,
    args = args,
    ci = ci,
    n_boot = n_boot,
    m_rate = m_rate,
    level = level,
    max_failure_rate = max_failure_rate,
    pre_standardized = pre_standardized,
    seed = seed,
    disable_parallelism = disable_parallelism,
    verbose = verbose,
    weights = weights,
    max_skip_rate = max_skip_rate
  ))
}

#' Query the split_nb auto-gate
#'
#' R binding of `split_nb_gate`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "3.2 Auto-gate query" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,weights See the canonical reference.
#' @return A list of class `c("split_nb_gate_result", "plskit_result")`.
#' @export
split_nb_gate <- function(
  X,
  weights = NULL
) {
  .plskit_call("split_nb_gate", list(
    X = X,
    weights = weights
  ))
}

#' Permutation null of PLS1 coefficients
#'
#' R binding of `pls1_perm_null`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "3.3 Permutation-null engine" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k,n_perm,return_perm_matrix,pre_standardized,seed,disable_parallelism,verbose,weights See the canonical reference.
#' @return A list of class `c("perm_null_result", "plskit_result")`.
#' @export
pls1_perm_null <- function(
  X,
  y,
  k,
  n_perm = NULL,
  return_perm_matrix = FALSE,
  pre_standardized = FALSE,
  seed = NULL,
  disable_parallelism = FALSE,
  verbose = FALSE,
  weights = NULL
) {
  .plskit_call("pls1_perm_null", list(
    X = X,
    y = y,
    k = k,
    n_perm = n_perm,
    return_perm_matrix = return_perm_matrix,
    pre_standardized = pre_standardized,
    seed = seed,
    disable_parallelism = disable_parallelism,
    verbose = verbose,
    weights = weights
  ))
}

#' Confirmatory test of a PLS3 signal
#'
#' R binding of `pls3_confirmatory_test`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "3.4 Confirmatory PLS3 omnibus test" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,Y,k,method,args,pre_standardized_X,pre_standardized_Y,seed,disable_parallelism,verbose See the canonical reference.
#' @return A list of class `c("confirmatory_test_result", "plskit_result")`.
#' @export
pls3_confirmatory_test <- function(
  X,
  Y,
  k = 1L,
  method,
  args = NULL,
  pre_standardized_X = FALSE,
  pre_standardized_Y = FALSE,
  seed = NULL,
  disable_parallelism = FALSE,
  verbose = FALSE
) {
  .plskit_call("pls3_confirmatory_test", list(
    X = X,
    Y = Y,
    k = k,
    method = method,
    args = args,
    pre_standardized_X = pre_standardized_X,
    pre_standardized_Y = pre_standardized_Y,
    seed = seed,
    disable_parallelism = disable_parallelism,
    verbose = verbose
  ))
}

#' Rotate PLS1 weights or a fitted PLS1 model
#'
#' R binding of `rotate`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "4.1 Rotation" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param model_or_W,method,L,args See the canonical reference.
#' @return A list of class `c("rotate_result", "plskit_result")`, or `c("pls1_result", "plskit_result")`, depending on the input.
#' @export
rotate <- function(
  model_or_W,
  method = "varimax",
  L = NULL,
  args = NULL
) {
  .plskit_call("rotate", list(
    model_or_W = model_or_W,
    method = method,
    L = L,
    args = args
  ))
}

#' Rotation-stability diagnostic for PLS1
#'
#' R binding of `pls1_rotation_stability`. Arguments, defaults and result fields are
#' documented once, in the canonical reference: section
#' "4.2 Rotation-stability diagnostic" of <https://github.com/pawlenartowicz/plskit/blob/main/_docs/python/api.md>.
#'
#' @param X,y,k,rotation_method,rotation_args,L,n_boot,m_rate,level,pre_standardized,seed,disable_parallelism,verbose,weights,max_skip_rate See the canonical reference.
#' @return A list of class `c("rotation_stability_result", "plskit_result")`.
#' @export
pls1_rotation_stability <- function(
  X,
  y,
  k,
  rotation_method = "varimax",
  rotation_args = NULL,
  L = NULL,
  n_boot = NULL,
  m_rate = NULL,
  level = NULL,
  pre_standardized = FALSE,
  seed = NULL,
  disable_parallelism = FALSE,
  verbose = FALSE,
  weights = NULL,
  max_skip_rate = NULL
) {
  .plskit_call("pls1_rotation_stability", list(
    X = X,
    y = y,
    k = k,
    rotation_method = rotation_method,
    rotation_args = rotation_args,
    L = L,
    n_boot = n_boot,
    m_rate = m_rate,
    level = level,
    pre_standardized = pre_standardized,
    seed = seed,
    disable_parallelism = disable_parallelism,
    verbose = verbose,
    weights = weights,
    max_skip_rate = max_skip_rate
  ))
}
