#!/usr/bin/env python3
"""Render the PLSKit.jl stubs, docstrings and result-type aliases.

Reads the plskit-bind registry dump and writes
`plskit-jl/src/generated.jl`: one stub per registry function, one
`const <Type> = PlsKitResult{:<Type>}` alias per result type, the
_docs/python/results.md field order the result conversion uses, and
the export list.

Julia call rule: a parameter that is required and not
keyword-only in Python is a Julia positional argument; every other
parameter is a Julia keyword, required when Python requires it
(`test_method` in the confirmatory tests).

Usage (from the workspace root):
    python3 scripts/render-jl-stubs.py                  # run the dump, rewrite
    python3 scripts/render-jl-stubs.py --check          # fail on drift
    python3 scripts/render-jl-stubs.py --dump reg.json [--check]

`--check` also fails when the dumped result fields (names and order)
differ from `_docs/python/results.md`. Plain python3, no deps.
"""

import argparse
import difflib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "plskit-jl" / "src" / "generated.jl"
RESULTS_MD = ROOT / "_docs" / "python" / "results.md"
DOCS_URL = "https://github.com/pawlenartowicz/plskit/blob/main/_docs/python"

RE_DOC_TYPE_HEADER = re.compile(r"^##\s+`(\w+)`")
RE_DOC_FIELD_ROW = re.compile(r"^\|\s*`(\w+)`\s*\|")


def load_dump(path):
    if path is not None:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    out = subprocess.run(
        ["cargo", "run", "-q", "-p", "plskit-bind", "--release",
         "--bin", "plskit-bind-dump"],
        cwd=ROOT, capture_output=True, text=True,
    )
    if out.returncode != 0:
        sys.exit(f"plskit-bind-dump failed:\n{out.stderr}")
    return json.loads(out.stdout)


def jl_literal(value):
    if value is None:
        return "nothing"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
        return f'"{escaped}"'
    raise ValueError(f"no Julia literal for default {value!r}")


def is_positional(param):
    return param["required"] and not param["keyword_only"]


def signature(fn):
    pos = [p["name"] for p in fn["params"] if is_positional(p)]
    kws = []
    for p in fn["params"]:
        if is_positional(p):
            continue
        kws.append(p["name"] if p["required"] else f"{p['name']}={jl_literal(p['default'])}")
    text = ", ".join(pos)
    if kws:
        text += "; " + ", ".join(kws)
    return f"{fn['name']}({text})"


def returns(fn):
    types = fn["result_types"]
    if not types:
        return "Vector{Float64}"
    return " or ".join(types)


def render_function(fn):
    name = fn["name"]
    names = ", ".join(p["name"] for p in fn["params"])
    return (
        f'"""\n'
        f"    {signature(fn)} -> {returns(fn)}\n"
        f"\n"
        f"Call Python's `plskit.{name}` with the same arguments and defaults.\n"
        f"Reference: [`{name}` in the Python API]({DOCS_URL}/api.md);\n"
        f"result fields: [results]({DOCS_URL}/results.md).\n"
        f'"""\n'
        f"function {signature(fn)}\n"
        f"    _call(:{name}; {names})\n"
        f"end\n"
    )


def render_alias(rt):
    name = rt["name"]
    fields = ", ".join(f"`{f['name']}`" for f in rt["fields"])
    return (
        f'"""\n'
        f"    {name}\n"
        f"\n"
        f"`PlsKitResult{{:{name}}}`, the Julia form of Python's `plskit.{name}`.\n"
        f"Fields: {fields}.\n"
        f"Reference: [results]({DOCS_URL}/results.md).\n"
        f'"""\n'
        f"const {name} = PlsKitResult{{:{name}}}\n"
    )


def render_export(names):
    lines, line = [], "export " + names[0]
    for n in names[1:]:
        if len(line) + len(n) + 2 > 92:
            lines.append(line + ",")
            line = "       " + n
        else:
            line += ", " + n
    lines.append(line)
    return "\n".join(lines) + "\n"


def render(dump):
    fns = dump["functions"]
    types = dump["result_types"]
    parts = [
        "# GENERATED by scripts/render-jl-stubs.py from the plskit-bind registry dump.\n"
        "# Do not edit by hand: re-run the script (CI fails on drift).\n",
        render_export([f["name"] for f in fns]),
        render_export([t["name"] for t in types]),
        "# Field order of every result type, as in _docs/python/results.md.\n"
        "const _RESULT_FIELDS = Dict{Symbol,Vector{Symbol}}(\n"
        + "".join(
            f"    :{t['name']} => [{', '.join(':' + f['name'] for f in t['fields'])}],\n"
            for t in types
        )
        + ")\n",
    ]
    parts += [render_alias(t) for t in types]
    parts += [render_function(f) for f in fns]
    return "\n".join(parts)


def results_md_fields():
    sections, current = {}, None
    for line in RESULTS_MD.read_text(encoding="utf-8").splitlines():
        header = RE_DOC_TYPE_HEADER.match(line)
        if header:
            current = header.group(1)
            sections[current] = []
            continue
        if line.startswith("## "):
            current = None
            continue
        if current is not None:
            row = RE_DOC_FIELD_ROW.match(line)
            if row:
                sections[current].append(row.group(1))
    return sections


def check_results_md(dump):
    doc = results_md_fields()
    issues = []
    for t in dump["result_types"]:
        dumped = [f["name"] for f in t["fields"]]
        documented = doc.get(t["name"])
        if documented is None:
            issues.append(f"{t['name']}: no section in {RESULTS_MD.relative_to(ROOT)}")
        elif documented != dumped:
            issues.append(f"{t['name']}: dump fields {dumped} != results.md {documented}")
    return issues


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dump", help="registry JSON (default: run plskit-bind-dump)")
    parser.add_argument("--check", action="store_true",
                        help="compare with the committed file instead of writing it")
    args = parser.parse_args()
    dump = load_dump(args.dump)
    text = render(dump)
    if not args.check:
        OUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {OUT.relative_to(ROOT)}")
        return 0
    issues = check_results_md(dump)
    committed = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if committed != text:
        diff = difflib.unified_diff(
            committed.splitlines(keepends=True), text.splitlines(keepends=True),
            fromfile="committed", tofile="fresh render",
        )
        issues.append("plskit-jl/src/generated.jl differs from a fresh render:\n"
                      + "".join(diff))
    if issues:
        print("== Julia stub drift ==")
        for line in issues:
            print(f"  {line}")
        print("Fix: python3 scripts/render-jl-stubs.py")
        return 1
    print("== Julia stubs: clean ==")
    return 0


if __name__ == "__main__":
    sys.exit(main())
